### ISSUE TITLE
return denominator = d;

### ISSUE THREAD

**Issue by wighawag** [ciscoheat/HaxeContracts#1]
return denominator = d; from the Rational example generates an error even if denominator is != 0. I assume this is due to the macro not picking the case where the return call expression contain the assignment ?

**Comment by ciscoheat** [comment]
Hm, it works for me with Haxe 3.1.3 straight from the example, are you using the same version? In the code the exact line is `return denominator = v;` (not d), could it be that simple?

**Comment by ciscoheat** [comment]
Sorry, I see that the documentation and code is not synced. It's `d` in the docs, `v` in the code, but both works for me. Did you do any modifications?

**Comment by wighawag** [comment]
I have this (only the invariant function)

```
class Rational implements HaxeContracts {
    public var numerator(default, default) : Int;
    public var denominator(default, set) : Int;

    public function new(numerator : Int, denominator : Int) {
        this.numerator = numerator;
        this.denominator = denominator;
    }

    public function toFloat() : Float {
        return numerator / denominator;
    }

    private function set_denominator(d : Int) {
        return denominator = d;
    }

    @invariant private function objectInvariant() {
        Contract.invariant(denominator != 0, "Denominator cannot be zero");
    }
}
```

using it like that :

```
var rational = new Rational(3,1);
rational.denominator = 2;
```

it throw exception at the second line 

if I use

```
private function set_denominator(d : Int) {
        denominator = d;
        return denominator;
    }
```

ther is no error

**Comment by ciscoheat** [comment]
Interesting, the exact same code works for me on Neko with Haxe 3.1.3. Which platform and version are you using?

**Comment by wighawag** [comment]
some haxe dev version, cannot be more precise rigth now

**Comment by ciscoheat** [comment]
Ok, I haven't tested it on any dev version yet, maybe there's been some internal changes. I'll take a look in the near future.

**Comment by ciscoheat** [comment]
This seems to work in 3.4, so closing this now.
