### ISSUE TITLE
HaxeContracts can be nicer with macros

### ISSUE THREAD

**Issue by kobi2187** [ciscoheat/HaxeContracts#2]
Hi,
I am familiar with eiffel's dbc, 
I was wondering if you can provide @:require, @:ensure, @:result, and @:old.
invariant is already in. (did I forget something?)
old is the incoming arguments. they can be cloned, and put in a hashtable called old.
so user will have access to old[arg1]. A generated anonymous object will give even nicer syntax.
I think this will make it less verbose and more enjoyable, therefore more utilized.

**Comment by ciscoheat** [comment]
Hello! Isn't the Contract.require/ensures methods that what you're looking for? "Old" isn't implemented, but it shouldn't be too hard.

**Comment by kobi2187** [comment]
oh yeah, sorry. didn't realize I can import \* and use them more easily.  (I used c# in the past and u had to qualify static functions with the class name in front.)
- is it possible to generate an anonymous object for 'old'?
  then you can do things like: "ensure (old.x < x);"

**Comment by ciscoheat** [comment]
Do you know how `old` and Eiffel works for identity vs reference comparisons? For example, will this pass:

``` haxe
function test(d : {name: String}) {
    ensures(old(d) == d);
    d.name = "Something else";
}
```

I've looked at the [language spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-367.pdf), but I can only take so much dry academic text in a lifetime... :) Any ideas?

**Comment by kobi2187** [comment]
well, the user can choose whether to use == or eq.
imo, the example should not pass.
it's enough to record the values that were passed as arguments. no need to bother with more than that.

**Comment by ciscoheat** [comment]
Why shouldn't it pass? `==` is identity comparison for `d` in this case.

**Comment by ciscoheat** [comment]
I'm quite sure it should pass, and the feature has been implemented now in version 0.12.0. Please check it out!

**Comment by ciscoheat** [comment]
`Contract.old` now works with any expression, so I'm closing this.

**Comment by kobi2187** [comment]
Hi Andreas. maybe I misunderstand but in the example, after a change in data, you asserted that it's still the same. 
`ensures(old(d) == d);`
that's why I said it should not pass. Did you mean `!=` or am I wrong on my side? 
for the record, there are now macros for "deep equal"

**Comment by ciscoheat** [comment]
Hi, according to the Eiffel documentation, `old` should test the value of its expression at method entry. Even though `d.name` changes, the reference to `d` will be the same, so that test should pass.
